config/routes.rb
Hw::Application.routes.draw do
  resources :appointments

  root :to => 'pages#home'  
  get '/pages/project_2', to: 'pages#project_2'
  get '/calendar', to: 'pages#calendar'
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  attr_accessible :day, :description, :month, :time, :year
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  # GET /appointments
  # GET /appointments.json

  
  def index
    @appointments = Appointment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @appointments }
    end
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
    @appointment = Appointment.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @appointment }
    end
  end

  # GET /appointments/new
  # GET /appointments/new.json
  def new
    @appointment = Appointment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @appointment }
    end
  end

  # GET /appointments/1/edit
  def edit
    @appointment = Appointment.find(params[:id])
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(params[:appointment])

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render json: @appointment, status: :created, location: @appointment }
      else
        format.html { render action: "new" }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /appointments/1
  # PUT /appointments/1.json
  def update
    @appointment = Appointment.find(params[:id])

    respond_to do |format|
      if @appointment.update_attributes(params[:appointment])
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment = Appointment.find(params[:id])
    @appointment.destroy

    respond_to do |format|
      format.html { redirect_to appointments_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/project_2_controller.rb
class Project2Controller < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/project_2_helper.rb
module Project2Helper
end

app/views/appointments/_form.html.erb
<%= form_for(@appointment) do |f| %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% @appointment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :month %><br />
    <%= f.number_field :month %>
  </div>
  <div class="field">
    <%= f.label :day %><br />
    <%= f.number_field :day %>
  </div>
  <div class="field">
    <%= f.label :year %><br />
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :time %><br />
    <%= f.text_field :time %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<h1>Editing appointment</h1>

<%= render 'form' %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<h1>Listing appointments</h1>

<table>
  <tr>
    <th>Month</th>
    <th>Day</th>
    <th>Year</th>
    <th>Time</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @appointments.each do |appointment| %>
  <tr>
    <td><%= appointment.month %></td>
    <td><%= appointment.day %></td>
    <td><%= appointment.year %></td>
    <td><%= appointment.time %></td>
    <td><%= appointment.description %></td>
    <td><%= link_to 'Show', appointment %></td>
    <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
    <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Appointment', new_appointment_path %>

app/views/appointments/new.html.erb
<h1>New appointment</h1>

<%= render 'form' %>

<%= link_to 'Back', appointments_path %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Month:</b>
  <%= @appointment.month %>
</p>

<p>
  <b>Day:</b>
  <%= @appointment.day %>
</p>

<p>
  <b>Year:</b>
  <%= @appointment.year %>
</p>

<p>
  <b>Time:</b>
  <%= @appointment.time %>
</p>

<p>
  <b>Description:</b>
  <%= @appointment.description %>
</p>


<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hw</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/calendar.html.erb
<!DOCTYPE html>

<html>

    <head>
        <link rel="stylesheet" type="text/css" href="assets/calendar.css">    
        <script src="assets/calendar.js"></script>
    </head>

    <body>
		<h1>Calendar!</h1>
        <div id="calendar">
            <script>calendar()</script>
        </div>

        </br>

		<form>
			Time</br> <select id="time_id">
							   <option value="00:00">00:00</option>
							   <option value="00:30">00:30</option>
							   <option value="01:00">01:00</option>
							   <option value="01:30">01:30</option>
							   <option value="02:00">02:00</option>
							   <option value="02:30">02:30</option>
							   <option value="03:00">03:00</option>
							   <option value="03:30">03:30</option>
							   <option value="04:00">04:00</option>
							   <option value="04:30">04:30</option>
							   <option value="05:00">05:00</option>
							   <option value="05:30">05:30</option>
							   <option value="06:00">06:00</option>
							   <option value="06:30">06:30</option>
							   <option value="07:00">07:00</option>
							   <option value="07:30">07:30</option>
							   <option value="08:00">08:00</option>
							   <option value="08:30">08:30</option>
							   <option value="09:00">09:00</option>
							   <option value="09:30">09:30</option>
							   <option value="10:00">10:00</option>
							   <option value="10:30">10:30</option>
							   <option value="11:00">11:00</option>
							   <option value="11:30">11:30</option>
							   <option value="12:00">12:00</option>
							   <option value="12:30">12:30</option>
							   <option value="13:00">13:00</option>
							   <option value="13:30">13:30</option>
							   <option value="14:00">14:00</option>
							   <option value="14:30">14:30</option>
							   <option value="15:00">15:00</option>
							   <option value="15:30">15:30</option>
							   <option value="16:00">16:00</option>
							   <option value="16:30">16:30</option>
							   <option value="17:00">17:00</option>
							   <option value="17:30">17:30</option>
							   <option value="18:00">18:00</option>
							   <option value="18:30">18:30</option>
							   <option value="19:00">19:00</option>
							   <option value="19:30">19:30</option>
							   <option value="20:00">20:00</option>
							   <option value="20:30">20:30</option>
							   <option value="21:00">21:00</option>
							   <option value="21:30">21:30</option>
							   <option value="22:00">22:00</option>
							   <option value="22:30">22:30</option>
							   <option value="23:00">23:00</option>
							   <option value="23:30">23:30</option>
							</select></br>
			Description</br> <input type="text" id="desc_id" /> </br>
		</form>		
		
		
    </body>

</html>

app/views/pages/home.html.erb
<h1>David Hua</h1>

<table>
	<thead>
		<tr>
			<th>Project Name</th>
			<th>Description</th>
			<th>URL</th>
		</tr>
	</thead>
	<tbody>
		<% PROJECTS.each do |project, data| %>
			<tr>
				<td><%= project %></td>
				<td><%= data['description'] %></td>
				<td><%= link_to data['url'], data['url'] %></td>
			</tr>
		<% end%>
	</tbody>
</table>

app/views/pages/project_2.html.erb
<h3> 
    For installing bootstrap, I followed the instructions on the Ruby on Rails Tutorial that is posted on iLearn. (bootstrap-sass) I used Google/RailsGuides to figure out how to set up a route for '/Pages/project_2'. 
</h3>